name: deadsnakes
description: install (pre-release) pythons from deadsnakes
inputs:
  python-version:
    description: python version to use, such as '3.9'
    required: true
runs:
  using: composite
  steps:
  - name: add deadsnakes ppa and install ${{ inputs.python-version }}
    run: ${{ github.action_path }}/bin/install-python ${{ inputs.python-version }}
    shell: bash
