name: deadsnakes
description: install (pre-release) pythons from deadsnakes
inputs:
  python-version:
    description: python version to use, such as '3.9'
    required: true
runs:
  using: node12
  main: dist/index.js
